### ISSUE TITLE
Адаптация под EDT 2020.6

### ISSUE THREAD

**Issue by YanSergey** [YanSergey/edt.cf_builder#6]
В EDT 2020.6 RC1 сборка CF прерывается ошибкой:
1. Через временную базу:
java.lang.NoSuchMethodError: 'void com._1c.g5.v8.dt.platform.services.core.runtimes.execution.IThickClientLauncher.exportConfigurationToCf(com._1c.g5.v8.dt.platform.services.core.runtimes.execution.ILaunchableRuntimeComponent, com._1c.g5.v8.dt.platform.services.model.InfobaseReference, com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionArguments, java.nio.file.Path)'
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.exportConfigurationToCfSimple(ExportProjectWorker.java:210)
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.exportConfigurationToCf(ExportProjectWorker.java:190)
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.proceedJob(ExportProjectWorker.java:113)
	at ru.yanygin.dt.cfbuilder.plugin.ui.JobDialog$16.run(JobDialog.java:942)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:164)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2. Через обычную ИБ:
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:469)
	at ru.yanygin.dt.cfbuilder.plugin.ui.JobDialog$15.lambda$0(JobDialog.java:875)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4005)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3633)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
Caused by: java.lang.NoSuchMethodError: 'void com._1c.g5.v8.dt.platform.services.core.runtimes.execution.IThickClientLauncher.exportConfigurationToCf(com._1c.g5.v8.dt.platform.services.core.runtimes.execution.ILaunchableRuntimeComponent, com._1c.g5.v8.dt.platform.services.model.InfobaseReference, com._1c.g5.v8.dt.platform.services.core.runtimes.execution.RuntimeExecutionArguments, java.nio.file.Path)'
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.exportConfigurationToCfSimple(ExportProjectWorker.java:210)
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.exportConfigurationToCf(ExportProjectWorker.java:190)
	at ru.yanygin.dt.cfbuilder.plugin.ui.ExportProjectWorker.proceedJob(ExportProjectWorker.java:113)
	at ru.yanygin.dt.cfbuilder.plugin.ui.JobDialog$15$1.run(JobDialog.java:882)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

![image](https://user-images.githubusercontent.com/24665801/99723760-a6c74a80-2ac3-11eb-94a7-b49214600352.png)

**Comment by YanSergey** [comment]
Реализовано в версии 1.3.0
